# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uClgGyoKotu7r317EIYtEamZ0DlrYOUg
"""

# ============================================================
# ADULT INCOME — FEATURE ENGINEERING AND EDA PROJECT
# Complete Google Colab Code - ONE CELL
# ============================================================

# -----------------------------
# 1. IMPORT LIBRARIES
# -----------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

pd.set_option("display.max_columns", None)
sns.set_style("whitegrid")

print("=" * 60)
print("ADULT INCOME — FEATURE ENGINEERING AND EDA")
print("=" * 60)


# -----------------------------
# 2. LOAD DATASET
# -----------------------------

columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income"
]

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

df = pd.read_csv(
    url,
    names=columns,
    skipinitialspace=True
)

print("\nDataset Loaded Successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])


# -----------------------------
# 3. DISPLAY FIRST 5 ROWS
# -----------------------------

print("\nFirst 5 Rows:")
display(df.head())


# -----------------------------
# 4. BASIC INFORMATION
# -----------------------------

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()


# -----------------------------
# 5. STATISTICAL SUMMARY
# -----------------------------

print("\nStatistical Summary:")
display(df.describe())


# -----------------------------
# 6. CHECK '?' MISSING VALUES
# -----------------------------

print("\nMissing Values Represented By '?':")

for column in df.columns:
    count = (df[column] == "?").sum()

    if count > 0:
        print(column, ":", count)


# -----------------------------
# 7. REPLACE '?' WITH NaN
# -----------------------------

df.replace("?", np.nan, inplace=True)

print("\nMissing Values After Replacement:")
print(df.isnull().sum())


# -----------------------------
# 8. HANDLE MISSING VALUES
# -----------------------------

categorical_columns = df.select_dtypes(
    include="object"
).columns

for column in categorical_columns:
    df[column] = df[column].fillna(
        df[column].mode()[0]
    )

print("\nMissing Values After Cleaning:")
print(df.isnull().sum())


# -----------------------------
# 9. CHECK DUPLICATES
# -----------------------------

duplicate_count = df.duplicated().sum()

print("\nNumber of Duplicate Rows:")
print(duplicate_count)

df.drop_duplicates(inplace=True)

print("Shape After Removing Duplicates:")
print(df.shape)


# ============================================================
#                         EDA
# ============================================================


# -----------------------------
# 10. INCOME DISTRIBUTION
# -----------------------------

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="income"
)

plt.title("Income Distribution")
plt.xlabel("Income")
plt.ylabel("Number of People")

plt.show()


# -----------------------------
# 11. AGE DISTRIBUTION
# -----------------------------

plt.figure(figsize=(8,5))

sns.histplot(
    data=df,
    x="age",
    bins=30,
    kde=True
)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")

plt.show()


# -----------------------------
# 12. GENDER DISTRIBUTION
# -----------------------------

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="sex"
)

plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Count")

plt.show()


# -----------------------------
# 13. EDUCATION DISTRIBUTION
# -----------------------------

plt.figure(figsize=(12,6))

sns.countplot(
    data=df,
    x="education"
)

plt.title("Education Distribution")
plt.xlabel("Education")
plt.ylabel("Count")

plt.xticks(rotation=60)

plt.show()


# -----------------------------
# 14. EDUCATION VS INCOME
# -----------------------------

plt.figure(figsize=(14,6))

sns.countplot(
    data=df,
    x="education",
    hue="income"
)

plt.title("Education vs Income")
plt.xlabel("Education")
plt.ylabel("Count")

plt.xticks(rotation=60)

plt.show()


# -----------------------------
# 15. AGE VS INCOME
# -----------------------------

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="income",
    y="age"
)

plt.title("Age vs Income")
plt.xlabel("Income")
plt.ylabel("Age")

plt.show()


# -----------------------------
# 16. HOURS PER WEEK VS INCOME
# -----------------------------

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="income",
    y="hours_per_week"
)

plt.title("Working Hours vs Income")
plt.xlabel("Income")
plt.ylabel("Hours Per Week")

plt.show()


# -----------------------------
# 17. WORKCLASS VS INCOME
# -----------------------------

plt.figure(figsize=(12,6))

sns.countplot(
    data=df,
    x="workclass",
    hue="income"
)

plt.title("Workclass vs Income")
plt.xlabel("Workclass")
plt.ylabel("Count")

plt.xticks(rotation=45)

plt.show()


# ============================================================
#                  FEATURE ENGINEERING
# ============================================================


# -----------------------------
# 18. AGE GROUP
# -----------------------------

df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 25, 40, 60, 100],
    labels=[
        "Young",
        "Adult",
        "Middle_Aged",
        "Senior"
    ]
)

print("\nAge Group Created:")
display(
    df[
        ["age", "age_group"]
    ].head(10)
)


# -----------------------------
# 19. TOTAL CAPITAL
# -----------------------------

df["total_capital"] = (
    df["capital_gain"] +
    df["capital_loss"]
)

print("\nTotal Capital Created:")
display(
    df[
        [
            "capital_gain",
            "capital_loss",
            "total_capital"
        ]
    ].head(10)
)


# -----------------------------
# 20. WORK HOURS CATEGORY
# -----------------------------

df["work_hours_category"] = pd.cut(
    df["hours_per_week"],
    bins=[0, 35, 45, 100],
    labels=[
        "Part-Time",
        "Full-Time",
        "Overtime"
    ]
)

print("\nWork Hours Category Created:")
display(
    df[
        [
            "hours_per_week",
            "work_hours_category"
        ]
    ].head(10)
)


# -----------------------------
# 21. EDUCATION LEVEL
# -----------------------------

education_mapping = {

    "Preschool": 0,
    "1st-4th": 1,
    "5th-6th": 2,
    "7th-8th": 3,
    "9th": 4,
    "10th": 5,
    "11th": 6,
    "12th": 7,
    "HS-grad": 8,
    "Some-college": 9,
    "Assoc-voc": 10,
    "Assoc-acdm": 10,
    "Bachelors": 11,
    "Masters": 12,
    "Prof-school": 13,
    "Doctorate": 14

}

df["education_level"] = df["education"].map(
    education_mapping
)

print("\nEducation Level Created:")

display(
    df[
        [
            "education",
            "education_level"
        ]
    ].head(10)
)


# -----------------------------
# 22. BINARY INCOME
# -----------------------------

df["income_binary"] = df["income"].map({
    "<=50K": 0,
    ">50K": 1
})

print("\nBinary Income Created:")

display(
    df[
        [
            "income",
            "income_binary"
        ]
    ].head(10)
)


# ============================================================
#               EDA AFTER FEATURE ENGINEERING
# ============================================================


# -----------------------------
# 23. AGE GROUP VS INCOME
# -----------------------------

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="age_group",
    hue="income"
)

plt.title("Age Group vs Income")
plt.xlabel("Age Group")
plt.ylabel("Count")

plt.show()


# -----------------------------
# 24. WORK HOURS CATEGORY VS INCOME
# -----------------------------

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="work_hours_category",
    hue="income"
)

plt.title("Working Hours Category vs Income")
plt.xlabel("Working Hours Category")
plt.ylabel("Count")

plt.show()


# -----------------------------
# 25. EDUCATION LEVEL VS INCOME
# -----------------------------

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="income",
    y="education_level"
)

plt.title("Education Level vs Income")
plt.xlabel("Income")
plt.ylabel("Education Level")

plt.show()


# -----------------------------
# 26. CAPITAL GAIN DISTRIBUTION
# -----------------------------

plt.figure(figsize=(8,5))

sns.histplot(
    data=df,
    x="capital_gain",
    bins=30
)

plt.title("Capital Gain Distribution")
plt.xlabel("Capital Gain")
plt.ylabel("Frequency")

plt.show()


# -----------------------------
# 27. CORRELATION HEATMAP
# -----------------------------

numeric_columns = [
    "age",
    "fnlwgt",
    "education_num",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "education_level",
    "total_capital",
    "income_binary"
]

correlation = df[numeric_columns].corr()

plt.figure(figsize=(10,8))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()


# ============================================================
#                    GROUP ANALYSIS
# ============================================================


# -----------------------------
# 28. INCOME BY EDUCATION
# -----------------------------

education_income = (
    df.groupby("education")["income_binary"]
    .mean()
    .sort_values(ascending=False)
)

print("\nAverage Income Probability by Education:")
print(education_income)


# -----------------------------
# 29. INCOME BY OCCUPATION
# -----------------------------

occupation_income = (
    df.groupby("occupation")["income_binary"]
    .mean()
    .sort_values(ascending=False)
)

print("\nAverage Income Probability by Occupation:")
print(occupation_income)


# -----------------------------
# 30. INCOME BY WORKCLASS
# -----------------------------

workclass_income = (
    df.groupby("workclass")["income_binary"]
    .mean()
    .sort_values(ascending=False)
)

print("\nAverage Income Probability by Workclass:")
print(workclass_income)


# ============================================================
#                    FINAL DATASET
# ============================================================


# -----------------------------
# 31. FINAL INFORMATION
# -----------------------------

print("\n" + "=" * 60)
print("FINAL DATASET")
print("=" * 60)

print("\nFinal Shape:")
print(df.shape)

print("\nFinal Columns:")
print(df.columns.tolist())

print("\nFinal Missing Values:")
print(df.isnull().sum())

print("\nFinal Dataset Preview:")
display(df.head(10))


# -----------------------------
# 32. SAVE CSV
# -----------------------------

filename = "adult_income_feature_engineered.csv"

df.to_csv(
    filename,
    index=False
)

print("\nCSV FILE CREATED SUCCESSFULLY!")
print(filename)


# -----------------------------
# 33. DOWNLOAD CSV
# -----------------------------

files.download(filename)

print("\nDownload started!")
print("=" * 60)
print("PROJECT 3 COMPLETED")
print("=" * 60)