# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iO7-lK9ufeucwhS7MdsuJ-XBub1kG5a0
"""

# ============================================================
# DIABETES SEVERITY - MULTINOMIAL LOGISTIC REGRESSION
# COMPLETE GOOGLE COLAB CODE - ONE CELL
# ============================================================

# ------------------------------------------------------------
# 1. IMPORT LIBRARIES
# ------------------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

from google.colab import files

pd.set_option("display.max_columns", None)
sns.set_style("whitegrid")

print("=" * 70)
print("DIABETES SEVERITY - MULTINOMIAL LOGISTIC REGRESSION")
print("=" * 70)


# ------------------------------------------------------------
# 2. LOAD DATASET
# ------------------------------------------------------------

# Diabetes dataset
url = "https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv"

df = pd.read_csv(url)

print("\nDataset Loaded Successfully!")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])


# ------------------------------------------------------------
# 3. DISPLAY FIRST 5 ROWS
# ------------------------------------------------------------

print("\nFirst 5 Rows:")
display(df.head())


# ------------------------------------------------------------
# 4. BASIC INFORMATION
# ------------------------------------------------------------

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()


# ------------------------------------------------------------
# 5. STATISTICAL SUMMARY
# ------------------------------------------------------------

print("\nStatistical Summary:")

display(df.describe())


# ------------------------------------------------------------
# 6. CHECK MISSING VALUES
# ------------------------------------------------------------

print("\nMissing Values:")

print(df.isnull().sum())


# ------------------------------------------------------------
# 7. CHECK DUPLICATES
# ------------------------------------------------------------

print("\nDuplicate Rows:")

print(df.duplicated().sum())


# ------------------------------------------------------------
# 8. REMOVE DUPLICATES
# ------------------------------------------------------------

df.drop_duplicates(inplace=True)

print("\nShape After Removing Duplicates:")

print(df.shape)


# ============================================================
#                         EDA
# ============================================================


# ------------------------------------------------------------
# 9. TARGET DISTRIBUTION
# ------------------------------------------------------------

plt.figure(figsize=(7, 5))

sns.countplot(
    data=df,
    x="Outcome"
)

plt.title("Diabetes Outcome Distribution")
plt.xlabel("Outcome")
plt.ylabel("Number of Patients")

plt.show()


# ------------------------------------------------------------
# 10. GLUCOSE DISTRIBUTION
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x="Glucose",
    bins=30,
    kde=True
)

plt.title("Glucose Distribution")
plt.xlabel("Glucose")
plt.ylabel("Frequency")

plt.show()


# ------------------------------------------------------------
# 11. BMI DISTRIBUTION
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x="BMI",
    bins=30,
    kde=True
)

plt.title("BMI Distribution")
plt.xlabel("BMI")
plt.ylabel("Frequency")

plt.show()


# ------------------------------------------------------------
# 12. AGE DISTRIBUTION
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x="Age",
    bins=30,
    kde=True
)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")

plt.show()


# ------------------------------------------------------------
# 13. GLUCOSE VS DIABETES
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Outcome",
    y="Glucose"
)

plt.title("Glucose vs Diabetes Outcome")
plt.xlabel("Diabetes Outcome")
plt.ylabel("Glucose")

plt.show()


# ------------------------------------------------------------
# 14. BMI VS DIABETES
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Outcome",
    y="BMI"
)

plt.title("BMI vs Diabetes Outcome")
plt.xlabel("Diabetes Outcome")
plt.ylabel("BMI")

plt.show()


# ------------------------------------------------------------
# 15. AGE VS DIABETES
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Outcome",
    y="Age"
)

plt.title("Age vs Diabetes Outcome")
plt.xlabel("Diabetes Outcome")
plt.ylabel("Age")

plt.show()


# ------------------------------------------------------------
# 16. CORRELATION HEATMAP
# ------------------------------------------------------------

plt.figure(figsize=(10, 8))

correlation = df.corr()

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Diabetes Dataset Correlation Heatmap")

plt.show()


# ============================================================
#                  FEATURE ENGINEERING
# ============================================================


# ------------------------------------------------------------
# 17. BMI CATEGORY
# ------------------------------------------------------------

df["BMI_Category"] = pd.cut(
    df["BMI"],
    bins=[0, 18.5, 25, 30, 100],
    labels=[
        "Underweight",
        "Normal",
        "Overweight",
        "Obese"
    ]
)

print("\nBMI Categories:")

display(
    df[
        ["BMI", "BMI_Category"]
    ].head(10)
)


# ------------------------------------------------------------
# 18. AGE CATEGORY
# ------------------------------------------------------------

df["Age_Category"] = pd.cut(
    df["Age"],
    bins=[0, 30, 45, 60, 100],
    labels=[
        "Young",
        "Adult",
        "Middle_Aged",
        "Senior"
    ]
)

print("\nAge Categories:")

display(
    df[
        ["Age", "Age_Category"]
    ].head(10)
)


# ------------------------------------------------------------
# 19. GLUCOSE CATEGORY
# ------------------------------------------------------------

df["Glucose_Category"] = pd.cut(
    df["Glucose"],
    bins=[0, 100, 125, 200, 300],
    labels=[
        "Normal",
        "Prediabetes",
        "High",
        "Very_High"
    ]
)

print("\nGlucose Categories:")

display(
    df[
        ["Glucose", "Glucose_Category"]
    ].head(10)
)


# ------------------------------------------------------------
# 20. INSULIN FEATURE
# ------------------------------------------------------------

df["Insulin_Glucose_Ratio"] = (
    df["Insulin"] /
    (df["Glucose"] + 1)
)

print("\nInsulin/Glucose Ratio:")

display(
    df[
        [
            "Insulin",
            "Glucose",
            "Insulin_Glucose_Ratio"
        ]
    ].head(10)
)


# ============================================================
#             CREATE DIABETES SEVERITY TARGET
# ============================================================

# Severity is created using glucose and BMI.
#
# 0 = Low Risk
# 1 = Moderate Risk
# 2 = High Risk
#
# This gives us a MULTI-CLASS target suitable
# for Multinomial Logistic Regression.


# ------------------------------------------------------------
# 21. CREATE SEVERITY TARGET
# ------------------------------------------------------------

def diabetes_severity(row):

    glucose = row["Glucose"]
    bmi = row["BMI"]

    if glucose < 100 and bmi < 25:
        return 0

    elif glucose < 126 and bmi < 30:
        return 1

    else:
        return 2


df["Severity"] = df.apply(
    diabetes_severity,
    axis=1
)


# ------------------------------------------------------------
# 22. SEVERITY LABELS
# ------------------------------------------------------------

severity_labels = {
    0: "Low Risk",
    1: "Moderate Risk",
    2: "High Risk"
}

df["Severity_Label"] = df["Severity"].map(
    severity_labels
)

print("\nSeverity Distribution:")

print(
    df["Severity_Label"].value_counts()
)


# ------------------------------------------------------------
# 23. SEVERITY VISUALIZATION
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.countplot(
    data=df,
    x="Severity_Label"
)

plt.title("Diabetes Severity Distribution")
plt.xlabel("Severity")
plt.ylabel("Number of Patients")

plt.show()


# ------------------------------------------------------------
# 24. GLUCOSE VS SEVERITY
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Severity_Label",
    y="Glucose"
)

plt.title("Glucose vs Diabetes Severity")
plt.xlabel("Severity")
plt.ylabel("Glucose")

plt.show()


# ------------------------------------------------------------
# 25. BMI VS SEVERITY
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Severity_Label",
    y="BMI"
)

plt.title("BMI vs Diabetes Severity")
plt.xlabel("Severity")
plt.ylabel("BMI")

plt.show()


# ============================================================
#                  PREPARE ML DATA
# ============================================================


# ------------------------------------------------------------
# 26. SELECT FEATURES
# ------------------------------------------------------------

features = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Insulin_Glucose_Ratio"
]

X = df[features]

y = df["Severity"]

print("\nFeatures Used:")

print(features)

print("\nTarget:")
print("Severity")


# ------------------------------------------------------------
# 27. TRAIN TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Data:")
print(X_train.shape)

print("\nTesting Data:")
print(X_test.shape)


# ============================================================
#                    FEATURE SCALING
# ============================================================


# ------------------------------------------------------------
# 28. STANDARD SCALER
# ------------------------------------------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)

print("\nFeature Scaling Completed!")


# ============================================================
#            MULTINOMIAL LOGISTIC REGRESSION
# ============================================================


# ------------------------------------------------------------
# 29. CREATE MODEL
# ------------------------------------------------------------

model = LogisticRegression(
    multi_class="multinomial",
    solver="lbfgs",
    max_iter=2000,
    random_state=42
)

model.fit(
    X_train_scaled,
    y_train
)

print("\nMultinomial Logistic Regression Model Trained!")


# ------------------------------------------------------------
# 30. PREDICTION
# ------------------------------------------------------------

y_pred = model.predict(
    X_test_scaled
)

y_probability = model.predict_proba(
    X_test_scaled
)


# ============================================================
#                    MODEL EVALUATION
# ============================================================


# ------------------------------------------------------------
# 31. ACCURACY
# ------------------------------------------------------------

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\n" + "=" * 60)
print("MODEL PERFORMANCE")
print("=" * 60)

print("\nAccuracy:")

print(accuracy)


# ------------------------------------------------------------
# 32. CLASSIFICATION REPORT
# ------------------------------------------------------------

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            "Low Risk",
            "Moderate Risk",
            "High Risk"
        ]
    )
)


# ------------------------------------------------------------
# 33. CONFUSION MATRIX
# ------------------------------------------------------------

cm = confusion_matrix(
    y_test,
    y_pred
)

plt.figure(figsize=(7, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        "Low Risk",
        "Moderate Risk",
        "High Risk"
    ],
    yticklabels=[
        "Low Risk",
        "Moderate Risk",
        "High Risk"
    ]
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()


# ============================================================
#                    MODEL COEFFICIENTS
# ============================================================


# ------------------------------------------------------------
# 34. COEFFICIENT TABLE
# ------------------------------------------------------------

coefficients = pd.DataFrame(
    model.coef_,
    columns=features,
    index=[
        "Low Risk",
        "Moderate Risk",
        "High Risk"
    ]
)

print("\nModel Coefficients:")

display(coefficients)


# ------------------------------------------------------------
# 35. COEFFICIENT VISUALIZATION
# ------------------------------------------------------------

plt.figure(figsize=(14, 6))

coefficients.T.plot(
    kind="bar",
    figsize=(14, 6)
)

plt.title(
    "Multinomial Logistic Regression Coefficients"
)

plt.xlabel("Features")
plt.ylabel("Coefficient")

plt.xticks(rotation=45)

plt.legend(
    title="Severity"
)

plt.show()


# ============================================================
#                 PREDICTION EXAMPLES
# ============================================================


# ------------------------------------------------------------
# 36. SHOW ACTUAL VS PREDICTED
# ------------------------------------------------------------

comparison = pd.DataFrame({

    "Actual": y_test.values,

    "Predicted": y_pred

})

comparison["Actual_Label"] = (
    comparison["Actual"]
    .map(severity_labels)
)

comparison["Predicted_Label"] = (
    comparison["Predicted"]
    .map(severity_labels)
)

print("\nActual vs Predicted:")

display(
    comparison.head(20)
)


# ============================================================
#                     SAVE DATASET
# ============================================================


# ------------------------------------------------------------
# 37. SAVE CLEANED DATASET
# ------------------------------------------------------------

df.to_csv(
    "diabetes_severity.csv",
    index=False
)

print("\nDataset saved as:")
print("diabetes_severity.csv")


# ------------------------------------------------------------
# 38. SAVE MODEL RESULTS
# ------------------------------------------------------------

results = pd.DataFrame({

    "Metric": [
        "Accuracy"
    ],

    "Value": [
        accuracy
    ]

})

results.to_csv(
    "diabetes_model_results.csv",
    index=False
)

print("\nModel results saved as:")
print("diabetes_model_results.csv")


# ============================================================
#                     DOWNLOAD FILES
# ============================================================

print("\nDownloading files...")

files.download(
    "diabetes_severity.csv"
)

files.download(
    "diabetes_model_results.csv"
)


# ============================================================
#                         SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("DIABETES SEVERITY PROJECT COMPLETED!")
print("=" * 70)

print("\nDataset:", "Diabetes")

print("Samples:", len(df))

print("Features used:", len(features))

print("\nAlgorithm:")
print("Multinomial Logistic Regression")

print("\nClasses:")
print("0 = Low Risk")
print("1 = Moderate Risk")
print("2 = High Risk")

print("\nAccuracy:")
print(round(accuracy * 100, 2), "%")

print("\nCSV files downloaded successfully!")
print("=" * 70)