# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-KLJ7opxVRVRIUeOglrPsoYmnyScYaT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
housing = fetch_california_housing(as_frame=True)
df = housing.frame
df.head()
#separateX and Y
X = df.drop("MedHouseVal", axis=1)
y = df["MedHouseVal"]
#Train-Test Split "80% of the data is used for training and 20% for testing."
X_train, X_test, y_train, y_test = train_test_split(
X,
y,
test_size=0.2,
random_state=42
)
print("Training data:", X_train.shape)
#LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
#eval
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
mae_lr = mean_absolute_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)
print("Linear Regression")
print("RMSE:", rmse_lr)
print("MAE :", mae_lr)
print("R2 :", r2_lr)
#Coefficents
coefficients = pd.DataFrame({
"Feature": X.columns,
"Coefficient": lr.coef_
})
print(coefficients)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)