# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MVYfV4fkaYvBw03az64sYVQvS7NGRA2T
"""

# ============================================================
# AUTO MPG - LINEAR REGRESSION, FEATURE SCALING & ENCODING
# COMPLETE GOOGLE COLAB CODE - ONE CELL
# ============================================================

# ------------------------------------------------------------
# 1. IMPORT LIBRARIES
# ------------------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from google.colab import files

pd.set_option("display.max_columns", None)
sns.set_style("whitegrid")

print("=" * 70)
print("AUTO MPG - LINEAR REGRESSION, SCALING & ENCODING")
print("=" * 70)


# ------------------------------------------------------------
# 2. LOAD DATASET
# ------------------------------------------------------------

url = "https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv"

df = pd.read_csv(url)

print("\nDataset Loaded Successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])


# ------------------------------------------------------------
# 3. DISPLAY FIRST 5 ROWS
# ------------------------------------------------------------

print("\nFirst 5 Rows:")
display(df.head())


# ------------------------------------------------------------
# 4. BASIC INFORMATION
# ------------------------------------------------------------

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()


# ------------------------------------------------------------
# 5. STATISTICAL SUMMARY
# ------------------------------------------------------------

print("\nStatistical Summary:")
display(df.describe(include="all"))


# ------------------------------------------------------------
# 6. CHECK MISSING VALUES
# ------------------------------------------------------------

print("\nMissing Values:")
print(df.isnull().sum())


# ------------------------------------------------------------
# 7. CHECK DUPLICATES
# ------------------------------------------------------------

print("\nDuplicate Rows:")
print(df.duplicated().sum())


# ------------------------------------------------------------
# 8. REMOVE DUPLICATES
# ------------------------------------------------------------

df.drop_duplicates(inplace=True)

print("\nShape After Removing Duplicates:")
print(df.shape)


# ------------------------------------------------------------
# 9. CONVERT HORSEPOWER TO NUMERIC
# ------------------------------------------------------------

df["horsepower"] = pd.to_numeric(
    df["horsepower"],
    errors="coerce"
)

print("\nMissing Values After Horsepower Conversion:")
print(df.isnull().sum())


# ------------------------------------------------------------
# 10. HANDLE MISSING HORSEPOWER
# ------------------------------------------------------------

df["horsepower"] = df["horsepower"].fillna(
    df["horsepower"].median()
)

print("\nMissing Values After Cleaning:")
print(df.isnull().sum())


# ============================================================
#                         EDA
# ============================================================


# ------------------------------------------------------------
# 11. MPG DISTRIBUTION
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x="mpg",
    bins=30,
    kde=True
)

plt.title("MPG Distribution")
plt.xlabel("Miles Per Gallon")
plt.ylabel("Frequency")

plt.show()


# ------------------------------------------------------------
# 12. HORSEPOWER DISTRIBUTION
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x="horsepower",
    bins=30,
    kde=True
)

plt.title("Horsepower Distribution")
plt.xlabel("Horsepower")
plt.ylabel("Frequency")

plt.show()


# ------------------------------------------------------------
# 13. WEIGHT VS MPG
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="weight",
    y="mpg",
    alpha=0.6
)

plt.title("Vehicle Weight vs MPG")
plt.xlabel("Weight")
plt.ylabel("MPG")

plt.show()


# ------------------------------------------------------------
# 14. HORSEPOWER VS MPG
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="horsepower",
    y="mpg",
    alpha=0.6
)

plt.title("Horsepower vs MPG")
plt.xlabel("Horsepower")
plt.ylabel("MPG")

plt.show()


# ------------------------------------------------------------
# 15. ACCELERATION VS MPG
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="acceleration",
    y="mpg",
    alpha=0.6
)

plt.title("Acceleration vs MPG")
plt.xlabel("Acceleration")
plt.ylabel("MPG")

plt.show()


# ------------------------------------------------------------
# 16. CYLINDERS VS MPG
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="cylinders",
    y="mpg"
)

plt.title("Cylinders vs MPG")
plt.xlabel("Cylinders")
plt.ylabel("MPG")

plt.show()


# ------------------------------------------------------------
# 17. MODEL YEAR VS MPG
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="year",
    y="mpg"
)

plt.title("Model Year vs MPG")
plt.xlabel("Model Year")
plt.ylabel("MPG")

plt.show()


# ------------------------------------------------------------
# 18. CORRELATION HEATMAP
# ------------------------------------------------------------

numeric_columns = [
    "mpg",
    "cylinders",
    "displacement",
    "horsepower",
    "weight",
    "acceleration",
    "year"
]

correlation = df[numeric_columns].corr()

plt.figure(figsize=(10, 8))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Auto MPG Correlation Heatmap")

plt.show()


# ============================================================
#                  FEATURE ENGINEERING
# ============================================================


# ------------------------------------------------------------
# 19. VEHICLE AGE
# ------------------------------------------------------------

df["vehicle_age"] = (
    df["year"].max() - df["year"]
)

print("\nVehicle Age Created:")

display(
    df[
        ["year", "vehicle_age"]
    ].head(10)
)


# ------------------------------------------------------------
# 20. HORSEPOWER CATEGORY
# ------------------------------------------------------------

df["horsepower_category"] = pd.cut(
    df["horsepower"],
    bins=[0, 100, 150, 1000],
    labels=[
        "Low",
        "Medium",
        "High"
    ]
)

print("\nHorsepower Category Created:")

display(
    df[
        ["horsepower", "horsepower_category"]
    ].head(10)
)


# ------------------------------------------------------------
# 21. WEIGHT CATEGORY
# ------------------------------------------------------------

df["weight_category"] = pd.cut(
    df["weight"],
    bins=[0, 2500, 3500, 5000],
    labels=[
        "Light",
        "Medium",
        "Heavy"
    ]
)

print("\nWeight Category Created:")

display(
    df[
        ["weight", "weight_category"]
    ].head(10)
)


# ============================================================
#                EDA AFTER FEATURE ENGINEERING
# ============================================================


# ------------------------------------------------------------
# 22. HORSEPOWER CATEGORY VS MPG
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="horsepower_category",
    y="mpg"
)

plt.title("Horsepower Category vs MPG")
plt.xlabel("Horsepower Category")
plt.ylabel("MPG")

plt.show()


# ------------------------------------------------------------
# 23. WEIGHT CATEGORY VS MPG
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="weight_category",
    y="mpg"
)

plt.title("Weight Category vs MPG")
plt.xlabel("Weight Category")
plt.ylabel("MPG")

plt.show()


# ============================================================
#                   MACHINE LEARNING
# ============================================================


# ------------------------------------------------------------
# 24. DEFINE FEATURES AND TARGET
# ------------------------------------------------------------

# Target:
# mpg

# Numerical features
numeric_features = [
    "cylinders",
    "displacement",
    "horsepower",
    "weight",
    "acceleration",
    "year",
    "origin"
]

# Categorical feature
categorical_features = [
    "horsepower_category",
    "weight_category"
]

X = df[
    numeric_features +
    categorical_features
]

y = df["mpg"]

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget:")
print("mpg")


# ------------------------------------------------------------
# 25. TRAIN TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)


# ============================================================
#                PREPROCESSING PIPELINE
# ============================================================


# ------------------------------------------------------------
# 26. NUMERICAL SCALING
# ------------------------------------------------------------

numeric_transformer = Pipeline(
    steps=[
        (
            "scaler",
            StandardScaler()
        )
    ]
)


# ------------------------------------------------------------
# 27. CATEGORICAL ENCODING
# ------------------------------------------------------------

categorical_transformer = Pipeline(
    steps=[
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)


# ------------------------------------------------------------
# 28. COLUMN TRANSFORMER
# ------------------------------------------------------------

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer,
            numeric_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ]
)


# ============================================================
#                 LINEAR REGRESSION MODEL
# ============================================================


# ------------------------------------------------------------
# 29. CREATE PIPELINE
# ------------------------------------------------------------

model = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "regressor",
            LinearRegression()
        )
    ]
)


# ------------------------------------------------------------
# 30. TRAIN MODEL
# ------------------------------------------------------------

model.fit(
    X_train,
    y_train
)

print("\nLinear Regression Model Trained Successfully!")


# ------------------------------------------------------------
# 31. PREDICTION
# ------------------------------------------------------------

y_pred = model.predict(
    X_test
)


# ============================================================
#                    MODEL EVALUATION
# ============================================================


# ------------------------------------------------------------
# 32. CALCULATE METRICS
# ------------------------------------------------------------

mse = mean_squared_error(
    y_test,
    y_pred
)

rmse = np.sqrt(mse)

mae = mean_absolute_error(
    y_test,
    y_pred
)

r2 = r2_score(
    y_test,
    y_pred
)


print("\n" + "=" * 60)
print("LINEAR REGRESSION RESULTS")
print("=" * 60)

print("MSE :", mse)
print("RMSE:", rmse)
print("MAE :", mae)
print("R²  :", r2)


# ============================================================
#                ACTUAL VS PREDICTED
# ============================================================


# ------------------------------------------------------------
# 33. COMPARISON TABLE
# ------------------------------------------------------------

comparison = pd.DataFrame({

    "Actual_MPG": y_test.values,

    "Predicted_MPG": y_pred

})

comparison["Error"] = (
    comparison["Actual_MPG"] -
    comparison["Predicted_MPG"]
)

print("\nActual vs Predicted MPG:")

display(
    comparison.head(20)
)


# ------------------------------------------------------------
# 34. ACTUAL VS PREDICTED PLOT
# ------------------------------------------------------------

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    y_pred,
    alpha=0.6
)

plt.xlabel("Actual MPG")
plt.ylabel("Predicted MPG")

plt.title(
    "Actual vs Predicted MPG"
)

plt.show()


# ------------------------------------------------------------
# 35. RESIDUAL PLOT
# ------------------------------------------------------------

residuals = (
    y_test -
    y_pred
)

plt.figure(figsize=(8, 5))

sns.histplot(
    residuals,
    bins=30,
    kde=True
)

plt.title("Residual Distribution")
plt.xlabel("Residual")
plt.ylabel("Frequency")

plt.show()


# ============================================================
#                 MODEL COEFFICIENTS
# ============================================================


# ------------------------------------------------------------
# 36. GET FEATURE NAMES
# ------------------------------------------------------------

trained_preprocessor = (
    model.named_steps["preprocessor"]
)

feature_names = (
    trained_preprocessor
    .get_feature_names_out()
)

coefficients = (
    model
    .named_steps["regressor"]
    .coef_
)


# ------------------------------------------------------------
# 37. COEFFICIENT TABLE
# ------------------------------------------------------------

coefficient_df = pd.DataFrame({

    "Feature": feature_names,

    "Coefficient": coefficients

})

coefficient_df["Absolute_Coefficient"] = (
    coefficient_df["Coefficient"].abs()
)

coefficient_df = coefficient_df.sort_values(
    "Absolute_Coefficient",
    ascending=False
)

print("\nFeature Coefficients:")

display(
    coefficient_df
)


# ------------------------------------------------------------
# 38. COEFFICIENT VISUALIZATION
# ------------------------------------------------------------

plt.figure(figsize=(12, 7))

sns.barplot(
    data=coefficient_df,
    x="Coefficient",
    y="Feature"
)

plt.title(
    "Linear Regression Feature Coefficients"
)

plt.xlabel("Coefficient")
plt.ylabel("Feature")

plt.show()


# ============================================================
#                    FINAL DATASET
# ============================================================


# ------------------------------------------------------------
# 39. FINAL DATASET INFORMATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL DATASET")
print("=" * 70)

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nFinal Dataset:")
display(df.head(10))


# ============================================================
#                      SAVE CSV
# ============================================================


# ------------------------------------------------------------
# 40. SAVE CLEANED DATASET
# ------------------------------------------------------------

df.to_csv(
    "auto_mpg_feature_engineered.csv",
    index=False
)

print("\nCSV Created:")
print("auto_mpg_feature_engineered.csv")


# ------------------------------------------------------------
# 41. SAVE MODEL RESULTS
# ------------------------------------------------------------

model_results = pd.DataFrame({

    "Metric": [
        "MSE",
        "RMSE",
        "MAE",
        "R2 Score"
    ],

    "Value": [
        mse,
        rmse,
        mae,
        r2
    ]

})

model_results.to_csv(
    "auto_mpg_model_results.csv",
    index=False
)

print("\nModel Results Created:")
print("auto_mpg_model_results.csv")


# ============================================================
#                       DOWNLOAD
# ============================================================

print("\nDownloading CSV files...")

files.download(
    "auto_mpg_feature_engineered.csv"
)

files.download(
    "auto_mpg_model_results.csv"
)


# ============================================================
#                         SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("AUTO MPG PROJECT COMPLETED SUCCESSFULLY!")
print("=" * 70)

print("\nDataset: Auto MPG")

print("Samples:", len(df))

print("\nTarget: MPG")

print("\nAlgorithm:")
print("Linear Regression")

print("\nPreprocessing:")
print("1. Missing Value Handling")
print("2. StandardScaler for numerical features")
print("3. OneHotEncoder for categorical features")

print("\nModel Performance:")
print("MSE :", round(mse, 4))
print("RMSE:", round(rmse, 4))
print("MAE :", round(mae, 4))
print("R²  :", round(r2, 4))

print("\nCSV files downloaded successfully!")

print("=" * 70)