# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skDre0ZelcG6mIpxfIwFgkTPgfkWw2Yf
"""

x=5.5
y=8.001234567
c='h'
s="hello"
l=[5.5,8.123,'x',"welcome"]
l.append(10)
print(l)
l.pop()
print(l)

x=5.5
y=8.001234567
c='h'
s="hello"
l=[5.5,8.123,'x',"welcome"]
l.append(10)
print(l)
l.pop()
print(l)
T=(5.5,8.123,'x',"welcome")#TUPLE

x=5.5
y=8.001234567
c='h'
s="hello"
l=[5.5,8.123,'x',"welcome"]
l.append(10)
print(l)
l.pop()
print(l)
d={"a":"apple","color":["red","orange","blue"]}
print(d)

def add(x,y):
  print("Hello")
  return (x+y)
add(2,9)

def add(x,y):
  print("Hello")
  return (x-y)
add(77,7)

def add(x,y):
  print("Hello")
  return (x*y)
add(63,1)

def add(x,y):
  print("Hello")
  return (x/y)
add(69,3)

def add(x,y):
  print("Hello")
  return (x%y)
add(45,18)

for i in range(5):
  print(i)
for j in range(-1,5):
  print(j)

for i in range(5):
  print(i)
  print("")
for j in range(5,0,-1):
  print(j)
  print("")

i=1
while(i<=5):
  print(i)
  i=i+1

a=5
b=6
c=7
if(a>b):
  print("a is greater")
elif(b>c):
  print("b is greater")
elif(c>a):
  print("c is greater")
else:
  print("none")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
#loadthe dataset
df = pd.read_csv("titanic.csv")
print(df.head())
print(df.shape)
print(df.columns)
#Target(y) = survived
#tounderstand the data set
print(df.info())
print(df.describe())
print(df.isnull().sum())#checkmissing values
#EDA
sns.countplot(x="survived", data=df)
plt.title("Titanic Survival Count")
plt.show()
#survivalby gender
sns.countplot(x="sex", hue="survived", data=df)
plt.title("Survival by Gender")
plt.show()
sns.countplot(x="pclass", hue="survived", data=df)
plt.title("Survival by Passenger Class")
plt.show()
#selectthe required features
features = ["pclass","sex","age","sibsp","parch","fare","embarked"]
X = df[features].copy()
y = df["survived"]
#fornumer is age use median //missing values
X["age"] = X["age"].fillna(X["age"].median())
#forcategorical colum use mode
X["embarked"] = X["embarked"].fillna(X["embarked"].mode()[0])
print(X.isnull().sum())
X = pd.get_dummies(X,columns=["sex", "embarked"],drop_first=True)
print(X.head())
#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42,stratify=y)
scaler = StandardScaler()
#FeatureScaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
#Logistic Regression
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)
print("Model training completed")
y_pred = model.predict(X_test_scaled)
print(y_pred[:20])