# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skDre0ZelcG6mIpxfIwFgkTPgfkWw2Yf
"""

x=5.5
y=8.001234567
c='h'
s="hello"
l=[5.5,8.123,'x',"welcome"]
l.append(10)
print(l)
l.pop()
print(l)

x=5.5
y=8.001234567
c='h'
s="hello"
l=[5.5,8.123,'x',"welcome"]
l.append(10)
print(l)
l.pop()
print(l)
T=(5.5,8.123,'x',"welcome")#TUPLE

x=5.5
y=8.001234567
c='h'
s="hello"
l=[5.5,8.123,'x',"welcome"]
l.append(10)
print(l)
l.pop()
print(l)
d={"a":"apple","color":["red","orange","blue"]}
print(d)

def add(x,y):
  print("Hello")
  return (x+y)
add(2,9)

def add(x,y):
  print("Hello")
  return (x-y)
add(77,7)

def add(x,y):
  print("Hello")
  return (x*y)
add(63,1)

def add(x,y):
  print("Hello")
  return (x/y)
add(69,3)

def add(x,y):
  print("Hello")
  return (x%y)
add(45,18)

for i in range(5):
  print(i)
for j in range(-1,5):
  print(j)

for i in range(5):
  print(i)
  print("")
for j in range(5,0,-1):
  print(j)
  print("")

i=1
while(i<=5):
  print(i)
  i=i+1

a=5
b=6
c=7
if(a>b):
  print("a is greater")
elif(b>c):
  print("b is greater")
elif(c>a):
  print("c is greater")
else:
  print("none")