# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pV-S1Qf948Oags5rqMyGvCacV1INKVx3
"""

# ============================================================
# CALIFORNIA HOUSING
# LINEAR REGRESSION AND REGULARISATION PROJECT
# COMPLETE GOOGLE COLAB CODE - ONE CELL
# ============================================================

# ------------------------------------------------------------
# 1. IMPORT LIBRARIES
# ------------------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import fetch_california_housing

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression, Ridge, Lasso

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from google.colab import files

pd.set_option("display.max_columns", None)
sns.set_style("whitegrid")

print("=" * 70)
print("CALIFORNIA HOUSING - LINEAR REGRESSION & REGULARISATION")
print("=" * 70)


# ------------------------------------------------------------
# 2. LOAD CALIFORNIA HOUSING DATASET
# ------------------------------------------------------------

housing = fetch_california_housing(as_frame=True)

df = housing.frame.copy()

print("\nDataset loaded successfully!")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])


# ------------------------------------------------------------
# 3. DISPLAY DATASET
# ------------------------------------------------------------

print("\nFirst 5 Rows:")
display(df.head())


# ------------------------------------------------------------
# 4. BASIC INFORMATION
# ------------------------------------------------------------

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()


# ------------------------------------------------------------
# 5. STATISTICAL SUMMARY
# ------------------------------------------------------------

print("\nStatistical Summary:")

display(df.describe())


# ------------------------------------------------------------
# 6. CHECK MISSING VALUES
# ------------------------------------------------------------

print("\nMissing Values:")

print(df.isnull().sum())


# ------------------------------------------------------------
# 7. CHECK DUPLICATES
# ------------------------------------------------------------

print("\nDuplicate Rows:")

print(df.duplicated().sum())


# ------------------------------------------------------------
# 8. REMOVE DUPLICATES
# ------------------------------------------------------------

df.drop_duplicates(inplace=True)

print("\nShape After Removing Duplicates:")

print(df.shape)


# ============================================================
#                         EDA
# ============================================================


# ------------------------------------------------------------
# 9. TARGET DISTRIBUTION
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.histplot(
    df["MedHouseVal"],
    bins=40,
    kde=True
)

plt.title("Distribution of Median House Value")
plt.xlabel("Median House Value ($100,000)")
plt.ylabel("Frequency")

plt.show()


# ------------------------------------------------------------
# 10. MEDIAN INCOME VS HOUSE VALUE
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="MedInc",
    y="MedHouseVal",
    alpha=0.4
)

plt.title("Median Income vs House Value")
plt.xlabel("Median Income")
plt.ylabel("Median House Value")

plt.show()


# ------------------------------------------------------------
# 11. HOUSE AGE VS HOUSE VALUE
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="HouseAge",
    y="MedHouseVal",
    alpha=0.4
)

plt.title("House Age vs House Value")
plt.xlabel("House Age")
plt.ylabel("Median House Value")

plt.show()


# ------------------------------------------------------------
# 12. ROOMS VS HOUSE VALUE
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="AveRooms",
    y="MedHouseVal",
    alpha=0.4
)

plt.title("Average Rooms vs House Value")
plt.xlabel("Average Rooms")
plt.ylabel("Median House Value")

plt.show()


# ------------------------------------------------------------
# 13. POPULATION VS HOUSE VALUE
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="Population",
    y="MedHouseVal",
    alpha=0.4
)

plt.title("Population vs House Value")
plt.xlabel("Population")
plt.ylabel("Median House Value")

plt.show()


# ------------------------------------------------------------
# 14. CORRELATION HEATMAP
# ------------------------------------------------------------

plt.figure(figsize=(10, 8))

correlation = df.corr()

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()


# ============================================================
#                  FEATURE AND TARGET
# ============================================================


# ------------------------------------------------------------
# 15. DEFINE X AND y
# ------------------------------------------------------------

X = df.drop(
    "MedHouseVal",
    axis=1
)

y = df["MedHouseVal"]

print("\nFeatures (X):")
print(X.columns.tolist())

print("\nTarget (y):")
print("MedHouseVal")


# ------------------------------------------------------------
# 16. TRAIN TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)


# ============================================================
#                    FEATURE SCALING
# ============================================================


# ------------------------------------------------------------
# 17. STANDARDIZATION
# ------------------------------------------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

print("\nFeature scaling completed!")


# ============================================================
#                  LINEAR REGRESSION
# ============================================================


# ------------------------------------------------------------
# 18. CREATE LINEAR REGRESSION MODEL
# ------------------------------------------------------------

linear_model = LinearRegression()

linear_model.fit(
    X_train_scaled,
    y_train
)

print("\nLinear Regression model trained!")


# ------------------------------------------------------------
# 19. LINEAR REGRESSION PREDICTION
# ------------------------------------------------------------

y_pred_linear = linear_model.predict(
    X_test_scaled
)


# ------------------------------------------------------------
# 20. LINEAR REGRESSION EVALUATION
# ------------------------------------------------------------

linear_mse = mean_squared_error(
    y_test,
    y_pred_linear
)

linear_rmse = np.sqrt(
    linear_mse
)

linear_mae = mean_absolute_error(
    y_test,
    y_pred_linear
)

linear_r2 = r2_score(
    y_test,
    y_pred_linear
)

print("\n" + "=" * 50)
print("LINEAR REGRESSION RESULTS")
print("=" * 50)

print("MSE :", linear_mse)
print("RMSE:", linear_rmse)
print("MAE :", linear_mae)
print("R²  :", linear_r2)


# ============================================================
#                       RIDGE
# ============================================================


# ------------------------------------------------------------
# 21. RIDGE REGRESSION
# ------------------------------------------------------------

ridge_model = Ridge(
    alpha=1.0
)

ridge_model.fit(
    X_train_scaled,
    y_train
)

print("\nRidge Regression model trained!")


# ------------------------------------------------------------
# 22. RIDGE PREDICTION
# ------------------------------------------------------------

y_pred_ridge = ridge_model.predict(
    X_test_scaled
)


# ------------------------------------------------------------
# 23. RIDGE EVALUATION
# ------------------------------------------------------------

ridge_mse = mean_squared_error(
    y_test,
    y_pred_ridge
)

ridge_rmse = np.sqrt(
    ridge_mse
)

ridge_mae = mean_absolute_error(
    y_test,
    y_pred_ridge
)

ridge_r2 = r2_score(
    y_test,
    y_pred_ridge
)

print("\n" + "=" * 50)
print("RIDGE REGRESSION RESULTS")
print("=" * 50)

print("MSE :", ridge_mse)
print("RMSE:", ridge_rmse)
print("MAE :", ridge_mae)
print("R²  :", ridge_r2)


# ============================================================
#                        LASSO
# ============================================================


# ------------------------------------------------------------
# 24. LASSO REGRESSION
# ------------------------------------------------------------

lasso_model = Lasso(
    alpha=0.01,
    max_iter=10000
)

lasso_model.fit(
    X_train_scaled,
    y_train
)

print("\nLasso Regression model trained!")


# ------------------------------------------------------------
# 25. LASSO PREDICTION
# ------------------------------------------------------------

y_pred_lasso = lasso_model.predict(
    X_test_scaled
)


# ------------------------------------------------------------
# 26. LASSO EVALUATION
# ------------------------------------------------------------

lasso_mse = mean_squared_error(
    y_test,
    y_pred_lasso
)

lasso_rmse = np.sqrt(
    lasso_mse
)

lasso_mae = mean_absolute_error(
    y_test,
    y_pred_lasso
)

lasso_r2 = r2_score(
    y_test,
    y_pred_lasso
)

print("\n" + "=" * 50)
print("LASSO REGRESSION RESULTS")
print("=" * 50)

print("MSE :", lasso_mse)
print("RMSE:", lasso_rmse)
print("MAE :", lasso_mae)
print("R²  :", lasso_r2)


# ============================================================
#                  MODEL COMPARISON
# ============================================================


# ------------------------------------------------------------
# 27. CREATE COMPARISON TABLE
# ------------------------------------------------------------

results = pd.DataFrame({

    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Lasso Regression"
    ],

    "MSE": [
        linear_mse,
        ridge_mse,
        lasso_mse
    ],

    "RMSE": [
        linear_rmse,
        ridge_rmse,
        lasso_rmse
    ],

    "MAE": [
        linear_mae,
        ridge_mae,
        lasso_mae
    ],

    "R2 Score": [
        linear_r2,
        ridge_r2,
        lasso_r2
    ]

})

print("\n" + "=" * 70)
print("MODEL COMPARISON")
print("=" * 70)

display(results)


# ------------------------------------------------------------
# 28. R² SCORE COMPARISON
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.barplot(
    data=results,
    x="Model",
    y="R2 Score"
)

plt.title("R² Score Comparison")
plt.xlabel("Model")
plt.ylabel("R² Score")

plt.xticks(rotation=20)

plt.show()


# ------------------------------------------------------------
# 29. RMSE COMPARISON
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.barplot(
    data=results,
    x="Model",
    y="RMSE"
)

plt.title("RMSE Comparison")
plt.xlabel("Model")
plt.ylabel("RMSE")

plt.xticks(rotation=20)

plt.show()


# ============================================================
#                  ACTUAL VS PREDICTED
# ============================================================


# ------------------------------------------------------------
# 30. LINEAR REGRESSION
# ------------------------------------------------------------

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    y_pred_linear,
    alpha=0.4
)

plt.xlabel("Actual House Value")
plt.ylabel("Predicted House Value")

plt.title(
    "Actual vs Predicted - Linear Regression"
)

plt.show()


# ------------------------------------------------------------
# 31. RIDGE
# ------------------------------------------------------------

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    y_pred_ridge,
    alpha=0.4
)

plt.xlabel("Actual House Value")
plt.ylabel("Predicted House Value")

plt.title(
    "Actual vs Predicted - Ridge Regression"
)

plt.show()


# ------------------------------------------------------------
# 32. LASSO
# ------------------------------------------------------------

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    y_pred_lasso,
    alpha=0.4
)

plt.xlabel("Actual House Value")
plt.ylabel("Predicted House Value")

plt.title(
    "Actual vs Predicted - Lasso Regression"
)

plt.show()


# ============================================================
#                  MODEL COEFFICIENTS
# ============================================================


# ------------------------------------------------------------
# 33. COMPARE COEFFICIENTS
# ------------------------------------------------------------

coefficients = pd.DataFrame({

    "Feature": X.columns,

    "Linear_Regression": linear_model.coef_,

    "Ridge": ridge_model.coef_,

    "Lasso": lasso_model.coef_

})

print("\nModel Coefficients:")

display(coefficients)


# ------------------------------------------------------------
# 34. COEFFICIENT VISUALIZATION
# ------------------------------------------------------------

coefficients_plot = coefficients.set_index(
    "Feature"
)

coefficients_plot.plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title("Model Coefficients Comparison")
plt.xlabel("Features")
plt.ylabel("Coefficient Value")

plt.xticks(rotation=45)

plt.show()


# ============================================================
#                  SAVE DATASET AS CSV
# ============================================================


# ------------------------------------------------------------
# 35. SAVE ORIGINAL DATASET
# ------------------------------------------------------------

df.to_csv(
    "california_housing.csv",
    index=False
)

print("\nOriginal dataset saved as:")
print("california_housing.csv")


# ------------------------------------------------------------
# 36. SAVE MODEL RESULTS
# ------------------------------------------------------------

results.to_csv(
    "california_housing_model_results.csv",
    index=False
)

print("\nModel results saved as:")
print("california_housing_model_results.csv")


# ------------------------------------------------------------
# 37. DOWNLOAD FILES
# ------------------------------------------------------------

print("\nDownloading CSV files...")

files.download(
    "california_housing.csv"
)

files.download(
    "california_housing_model_results.csv"
)


# ============================================================
#                         FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PROJECT COMPLETED SUCCESSFULLY!")
print("=" * 70)

print("\nDataset:")
print("California Housing")

print("\nNumber of Samples:")
print(len(df))

print("\nNumber of Features:")
print(len(X.columns))

print("\nModels Used:")
print("1. Linear Regression")
print("2. Ridge Regression")
print("3. Lasso Regression")

print("\nBest Model Based on R²:")

best_model = results.loc[
    results["R2 Score"].idxmax(),
    "Model"
]

print(best_model)

print("\nBest R² Score:")

print(
    results["R2 Score"].max()
)

print("\nCSV files downloaded successfully!")