# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bSE9lBiT3jtiApdnU4wZ2AaZYW9gMxax
"""

# ============================================================
# PROJECT 9: HEART DISEASE - RANDOM FOREST ENSEMBLE
# ============================================================

# Install/import required libraries
!pip -q install ucimlrepo

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix,
    roc_auc_score, roc_curve
)

from google.colab import files

# ------------------------------------------------------------
# 1. LOAD HEART DISEASE DATASET
# ------------------------------------------------------------

print("Loading UCI Heart Disease dataset...")

heart_disease = fetch_ucirepo(id=45)

X = heart_disease.data.features
y = heart_disease.data.targets

df = pd.concat([X, y], axis=1)

print("\nDataset loaded successfully!")
print("Shape:", df.shape)

# ------------------------------------------------------------
# 2. BASIC DATA INSPECTION
# ------------------------------------------------------------

print("\n========== FIRST 5 ROWS ==========")
display(df.head())

print("\n========== DATASET INFO ==========")
print(df.info())

print("\n========== MISSING VALUES ==========")
print(df.isnull().sum())

print("\n========== DUPLICATES ==========")
print("Duplicate rows:", df.duplicated().sum())

print("\n========== STATISTICS ==========")
display(df.describe())

# ------------------------------------------------------------
# 3. CLEAN DATA
# ------------------------------------------------------------

# Convert all columns to numeric where possible
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Remove duplicates
df = df.drop_duplicates()

# Fill missing numerical values with median
for col in df.columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

# UCI target is usually named 'num'
# Convert multiclass target (0-4) into binary:
# 0 = No Heart Disease
# 1-4 = Heart Disease

target_column = "num"

if target_column not in df.columns:
    # Handle possible alternate target column names
    possible_targets = ["target", "Target", "heart_disease"]
    found = None

    for col in possible_targets:
        if col in df.columns:
            found = col
            break

    if found is not None:
        target_column = found
    else:
        target_column = df.columns[-1]

df["target"] = (df[target_column] > 0).astype(int)

if target_column != "target":
    df = df.drop(columns=[target_column])

print("\n========== CLEANED DATA ==========")
print("Shape:", df.shape)
display(df.head())

print("\nTarget distribution:")
print(df["target"].value_counts())

# ------------------------------------------------------------
# 4. EDA
# ------------------------------------------------------------

plt.figure(figsize=(7,5))
sns.countplot(data=df, x="target")
plt.title("Heart Disease Distribution")
plt.xlabel("Target (0 = No Disease, 1 = Disease)")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(
    data=df,
    x="age",
    hue="target",
    kde=True,
    bins=20
)
plt.title("Age Distribution by Heart Disease")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df, x="target", y="chol")
plt.title("Cholesterol vs Heart Disease")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df, x="target", y="thalach")
plt.title("Maximum Heart Rate vs Heart Disease")
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(
    df.corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Correlation Heatmap")
plt.show()

# ------------------------------------------------------------
# 5. FEATURES AND TARGET
# ------------------------------------------------------------

X = df.drop("target", axis=1)
y = df["target"]

# ------------------------------------------------------------
# 6. TRAIN-TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

# ------------------------------------------------------------
# 7. RANDOM FOREST MODEL
# ------------------------------------------------------------

rf_model = RandomForestClassifier(
    n_estimators=200,
    criterion="gini",
    max_depth=6,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("\nRandom Forest model trained successfully!")

# ------------------------------------------------------------
# 8. PREDICTION
# ------------------------------------------------------------

y_pred = rf_model.predict(X_test)
y_prob = rf_model.predict_proba(X_test)[:, 1]

# ------------------------------------------------------------
# 9. EVALUATION
# ------------------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
roc_auc = roc_auc_score(y_test, y_prob)

print("\n========== RANDOM FOREST RESULTS ==========")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")
print(f"ROC-AUC   : {roc_auc:.4f}")

print("\n========== CLASSIFICATION REPORT ==========")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=["No Disease", "Disease"],
        zero_division=0
    )
)

# ------------------------------------------------------------
# 10. CONFUSION MATRIX
# ------------------------------------------------------------

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["No Disease", "Disease"],
    yticklabels=["No Disease", "Disease"]
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Random Forest Confusion Matrix")
plt.show()

# ------------------------------------------------------------
# 11. ROC CURVE
# ------------------------------------------------------------

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure(figsize=(7,5))
plt.plot(
    fpr,
    tpr,
    label=f"Random Forest (AUC = {roc_auc:.3f})"
)

plt.plot([0, 1], [0, 1], linestyle="--")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Random Forest")
plt.legend()
plt.show()

# ------------------------------------------------------------
# 12. FEATURE IMPORTANCE
# ------------------------------------------------------------

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print("\n========== FEATURE IMPORTANCE ==========")
display(feature_importance)

plt.figure(figsize=(10,6))

sns.barplot(
    data=feature_importance,
    x="Importance",
    y="Feature"
)

plt.title("Random Forest Feature Importance")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.show()

# ------------------------------------------------------------
# 13. ACTUAL VS PREDICTED
# ------------------------------------------------------------

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred,
    "Probability_Disease": y_prob
})

print("\n========== ACTUAL VS PREDICTED ==========")
display(comparison.head(20))

# ------------------------------------------------------------
# 14. SAVE RESULTS
# ------------------------------------------------------------

df.to_csv("heart_random_forest_cleaned.csv", index=False)

comparison.to_csv(
    "heart_random_forest_predictions.csv",
    index=False
)

feature_importance.to_csv(
    "heart_random_forest_feature_importance.csv",
    index=False
)

results = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],
    "Score": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ]
})

results.to_csv(
    "heart_random_forest_results.csv",
    index=False
)

print("\nFiles created:")
print("1. heart_random_forest_cleaned.csv")
print("2. heart_random_forest_predictions.csv")
print("3. heart_random_forest_feature_importance.csv")
print("4. heart_random_forest_results.csv")

# Download main cleaned dataset
files.download("heart_random_forest_cleaned.csv")

print("\n================================================")
print("PROJECT 9 COMPLETED SUCCESSFULLY!")
print("================================================")