# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8jbAhmi9XVfIM5RIKti_4ybFpLKB3-T
"""

# ============================================================
# TITANIC SURVIVAL — PREPROCESSING PIPELINE & CLEANED DATASET
# ============================================================

# 1. Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

print("=" * 65)
print("TITANIC SURVIVAL — PREPROCESSING PIPELINE")
print("=" * 65)

# ============================================================
# 2. Upload Dataset
# ============================================================

print("\nUpload your titanic.csv file:")
uploaded = files.upload()

file_name = next(iter(uploaded))
df = pd.read_csv(file_name)

print("\nDataset loaded successfully!")
print("Original Dataset Shape:", df.shape)

print("\nFirst 5 Rows:")
display(df.head())

# ============================================================
# 3. Dataset Inspection
# ============================================================

print("\n" + "=" * 65)
print("DATASET INSPECTION")
print("=" * 65)

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nStatistical Summary:")
display(df.describe(include="all").T)

# ============================================================
# 4. Remove Duplicate Rows
# ============================================================

df = df.drop_duplicates()

print("\nDataset Shape After Removing Duplicates:", df.shape)

# ============================================================
# 5. Select Features and Target
# ============================================================

features = [
    "pclass",
    "sex",
    "age",
    "sibsp",
    "parch",
    "fare",
    "embarked"
]

target = "survived"

X = df[features]
y = df[target]

print("\nSelected Features:")
print(features)

print("\nTarget Variable:")
print(target)

# ============================================================
# 6. Train-Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

# ============================================================
# 7. Identify Numerical and Categorical Features
# ============================================================

numeric_features = [
    "pclass",
    "age",
    "sibsp",
    "parch",
    "fare"
]

categorical_features = [
    "sex",
    "embarked"
]

print("\nNumerical Features:")
print(numeric_features)

print("\nCategorical Features:")
print(categorical_features)

# ============================================================
# 8. Numerical Preprocessing
# ============================================================

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# ============================================================
# 9. Categorical Preprocessing
# ============================================================

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False
    ))
])

# ============================================================
# 10. Create Column Transformer
# ============================================================

preprocessor = ColumnTransformer([
    ("numerical", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

print("\nPreprocessing pipeline created successfully!")

# ============================================================
# 11. Fit and Transform Training Data
# ============================================================

X_train_processed = preprocessor.fit_transform(X_train)

# Transform test data
X_test_processed = preprocessor.transform(X_test)

print("\nTraining data processed!")
print("Processed Training Shape:", X_train_processed.shape)

print("Processed Testing Shape:", X_test_processed.shape)

# ============================================================
# 12. Get Processed Feature Names
# ============================================================

feature_names = preprocessor.get_feature_names_out()

print("\nProcessed Feature Names:")
print(feature_names)

# ============================================================
# 13. Create Cleaned Dataset
# ============================================================

X_processed = preprocessor.fit_transform(X)

feature_names = preprocessor.get_feature_names_out()

cleaned_df = pd.DataFrame(
    X_processed,
    columns=feature_names
)

# Add target column
cleaned_df["survived"] = y.values

print("\n" + "=" * 65)
print("CLEANED DATASET")
print("=" * 65)

print("\nCleaned Dataset Shape:", cleaned_df.shape)

display(cleaned_df.head(10))

# ============================================================
# 14. Check Missing Values After Processing
# ============================================================

print("\nMissing Values After Preprocessing:")
print(cleaned_df.isnull().sum().sum())

# ============================================================
# 15. Check Data Types
# ============================================================

print("\nData Types:")
print(cleaned_df.dtypes)

# ============================================================
# 16. Save Cleaned Dataset
# ============================================================

cleaned_file = "titanic_cleaned.csv"

cleaned_df.to_csv(
    cleaned_file,
    index=False
)

print("\nCleaned dataset saved as:", cleaned_file)

# ============================================================
# 17. Download Cleaned Dataset
# ============================================================

files.download(cleaned_file)

# ============================================================
# 18. Visualization — Before vs After
# ============================================================

plt.figure(figsize=(7,4))

plt.bar(
    ["Original Dataset", "Cleaned Dataset"],
    [df.shape[1], cleaned_df.shape[1]]
)

plt.title("Dataset Features Before and After Preprocessing")
plt.ylabel("Number of Features")

plt.show()

# ============================================================
# 19. Preprocessing Summary
# ============================================================

print("\n" + "=" * 65)
print("PREPROCESSING SUMMARY")
print("=" * 65)

print("""
1. Dataset was loaded successfully.
2. Duplicate records were removed.
3. Relevant features were selected.
4. Numerical missing values were handled using median imputation.
5. Categorical missing values were handled using most-frequent imputation.
6. Numerical features were standardized using StandardScaler.
7. Categorical features were converted using OneHotEncoder.
8. ColumnTransformer was used to combine preprocessing steps.
9. Training and testing data were processed separately.
10. A cleaned dataset was created and exported as CSV.
""")

print("=" * 65)
print("PROJECT 2 COMPLETED SUCCESSFULLY!")
print("=" * 65)