# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZH2F6Bl5-lSAlJXNmTy6M2N_9RsRvJI1
"""

# ============================================================
# PROJECT 10: HEART DISEASE
# XGBOOST + LIGHTGBM + SHAP INTERPRETABILITY
# ============================================================

!pip -q install xgboost lightgbm shap ucimlrepo

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from google.colab import files

# ============================================================
# 1. LOAD DATASET
# ============================================================

print("Loading UCI Heart Disease dataset...")

heart_disease = fetch_ucirepo(id=45)

X = heart_disease.data.features
y = heart_disease.data.targets

df = pd.concat([X, y], axis=1)

print("\nDataset loaded successfully!")
print("Original shape:", df.shape)

# ============================================================
# 2. BASIC INSPECTION
# ============================================================

print("\n========== FIRST 5 ROWS ==========")
display(df.head())

print("\n========== DATA TYPES ==========")
print(df.dtypes)

print("\n========== MISSING VALUES ==========")
print(df.isnull().sum())

print("\n========== DUPLICATES ==========")
print("Duplicate rows:", df.duplicated().sum())

# ============================================================
# 3. CLEAN DATA
# ============================================================

# Convert columns to numeric
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Remove duplicate rows
df = df.drop_duplicates()

# Fill missing values with median
for col in df.columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

# Detect target column
if "num" in df.columns:
    target_column = "num"
elif "target" in df.columns:
    target_column = "target"
else:
    target_column = df.columns[-1]

# Convert UCI target:
# 0 = No Disease
# 1,2,3,4 = Disease

df["target"] = (df[target_column] > 0).astype(int)

if target_column != "target":
    df = df.drop(columns=[target_column])

print("\n========== CLEANED DATA ==========")
print("Shape:", df.shape)

display(df.head())

print("\nTarget distribution:")
print(df["target"].value_counts())

# ============================================================
# 4. EXPLORATORY DATA ANALYSIS
# ============================================================

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="target"
)

plt.title("Heart Disease Distribution")
plt.xlabel("Target (0 = No Disease, 1 = Disease)")
plt.ylabel("Count")
plt.show()


plt.figure(figsize=(8,5))

sns.histplot(
    data=df,
    x="age",
    hue="target",
    kde=True,
    bins=20
)

plt.title("Age Distribution by Heart Disease")
plt.show()


plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="target",
    y="chol"
)

plt.title("Cholesterol vs Heart Disease")
plt.show()


plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="target",
    y="thalach"
)

plt.title("Maximum Heart Rate vs Heart Disease")
plt.show()


plt.figure(figsize=(12,8))

sns.heatmap(
    df.corr(),
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

# ============================================================
# 5. FEATURES AND TARGET
# ============================================================

X = df.drop("target", axis=1)
y = df["target"]

# ============================================================
# 6. TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples :", len(X_test))

# ============================================================
# 7. XGBOOST MODEL
# ============================================================

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)
xgb_prob = xgb_model.predict_proba(X_test)[:, 1]

# ============================================================
# 8. LIGHTGBM MODEL
# ============================================================

lgbm_model = LGBMClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    num_leaves=15,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    verbosity=-1
)

lgbm_model.fit(X_train, y_train)

lgbm_pred = lgbm_model.predict(X_test)
lgbm_prob = lgbm_model.predict_proba(X_test)[:, 1]

# ============================================================
# 9. EVALUATION FUNCTION
# ============================================================

def evaluate_model(name, y_true, y_pred, y_prob):

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(
        y_true,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        zero_division=0
    )

    auc = roc_auc_score(
        y_true,
        y_prob
    )

    print("\n======================================")
    print(name)
    print("======================================")

    print(f"Accuracy  : {accuracy:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1 Score  : {f1:.4f}")
    print(f"ROC-AUC   : {auc:.4f}")

    print("\nClassification Report:")
    print(
        classification_report(
            y_true,
            y_pred,
            target_names=["No Disease", "Disease"],
            zero_division=0
        )
    )

    return [
        accuracy,
        precision,
        recall,
        f1,
        auc
    ]


# Evaluate XGBoost
xgb_results = evaluate_model(
    "XGBoost",
    y_test,
    xgb_pred,
    xgb_prob
)

# Evaluate LightGBM
lgbm_results = evaluate_model(
    "LightGBM",
    y_test,
    lgbm_pred,
    lgbm_prob
)

# ============================================================
# 10. MODEL COMPARISON
# ============================================================

comparison = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],

    "XGBoost": xgb_results,

    "LightGBM": lgbm_results
})

print("\n========== MODEL COMPARISON ==========")
display(comparison)

comparison.set_index("Metric").plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("XGBoost vs LightGBM")
plt.ylabel("Score")
plt.ylim(0,1)
plt.xticks(rotation=0)
plt.show()

# ============================================================
# 11. CONFUSION MATRIX - XGBOOST
# ============================================================

cm_xgb = confusion_matrix(
    y_test,
    xgb_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm_xgb,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["No Disease", "Disease"],
    yticklabels=["No Disease", "Disease"]
)

plt.title("XGBoost Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ============================================================
# 12. CONFUSION MATRIX - LIGHTGBM
# ============================================================

cm_lgbm = confusion_matrix(
    y_test,
    lgbm_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm_lgbm,
    annot=True,
    fmt="d",
    cmap="Greens",
    xticklabels=["No Disease", "Disease"],
    yticklabels=["No Disease", "Disease"]
)

plt.title("LightGBM Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ============================================================
# 13. FEATURE IMPORTANCE - XGBOOST
# ============================================================

xgb_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": xgb_model.feature_importances_
})

xgb_importance = xgb_importance.sort_values(
    by="Importance",
    ascending=False
)

print("\n========== XGBOOST FEATURE IMPORTANCE ==========")
display(xgb_importance)

plt.figure(figsize=(10,6))

sns.barplot(
    data=xgb_importance,
    x="Importance",
    y="Feature"
)

plt.title("XGBoost Feature Importance")
plt.show()

# ============================================================
# 14. FEATURE IMPORTANCE - LIGHTGBM
# ============================================================

lgbm_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": lgbm_model.feature_importances_
})

lgbm_importance = lgbm_importance.sort_values(
    by="Importance",
    ascending=False
)

print("\n========== LIGHTGBM FEATURE IMPORTANCE ==========")
display(lgbm_importance)

plt.figure(figsize=(10,6))

sns.barplot(
    data=lgbm_importance,
    x="Importance",
    y="Feature"
)

plt.title("LightGBM Feature Importance")
plt.show()

# ============================================================
# 15. SHAP INTERPRETABILITY - XGBOOST
# ============================================================

print("\nCalculating SHAP values for XGBoost...")

explainer_xgb = shap.TreeExplainer(xgb_model)

shap_values_xgb = explainer_xgb.shap_values(X_test)

# SHAP summary plot
print("\n========== SHAP SUMMARY - XGBOOST ==========")

shap.summary_plot(
    shap_values_xgb,
    X_test,
    show=True
)

# ============================================================
# 16. SHAP BAR PLOT
# ============================================================

print("\n========== SHAP FEATURE IMPORTANCE ==========")

shap.summary_plot(
    shap_values_xgb,
    X_test,
    plot_type="bar",
    show=True
)

# ============================================================
# 17. SHAP WATERFALL FOR ONE PATIENT
# ============================================================

print("\n========== SHAP WATERFALL ==========")

# Select first test sample
sample_index = 0

sample = X_test.iloc[[sample_index]]

print("Patient data:")
display(sample)

print(
    "Actual class:",
    y_test.iloc[sample_index]
)

print(
    "Predicted class:",
    xgb_pred[sample_index]
)

print(
    "Disease probability:",
    round(xgb_prob[sample_index], 4)
)

# Create SHAP explanation
explanation = shap.Explanation(
    values=shap_values_xgb[sample_index],
    base_values=explainer_xgb.expected_value,
    data=sample.iloc[0].values,
    feature_names=X.columns.tolist()
)

shap.plots.waterfall(
    explanation,
    max_display=14
)

# ============================================================
# 18. ROC CURVES
# ============================================================

from sklearn.metrics import roc_curve

fpr_xgb, tpr_xgb, _ = roc_curve(
    y_test,
    xgb_prob
)

fpr_lgbm, tpr_lgbm, _ = roc_curve(
    y_test,
    lgbm_prob
)

plt.figure(figsize=(8,6))

plt.plot(
    fpr_xgb,
    tpr_xgb,
    label=f"XGBoost AUC = {roc_auc_score(y_test, xgb_prob):.3f}"
)

plt.plot(
    fpr_lgbm,
    tpr_lgbm,
    label=f"LightGBM AUC = {roc_auc_score(y_test, lgbm_prob):.3f}"
)

plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.show()

# ============================================================
# 19. PREDICTION COMPARISON
# ============================================================

prediction_comparison = pd.DataFrame({
    "Actual": y_test.values,
    "XGBoost_Predicted": xgb_pred,
    "XGBoost_Probability": xgb_prob,
    "LightGBM_Predicted": lgbm_pred,
    "LightGBM_Probability": lgbm_prob
})

print("\n========== PREDICTION COMPARISON ==========")
display(prediction_comparison.head(20))

# ============================================================
# 20. SAVE OUTPUT FILES
# ============================================================

df.to_csv(
    "heart_xgboost_lightgbm_cleaned.csv",
    index=False
)

comparison.to_csv(
    "xgboost_lightgbm_model_comparison.csv",
    index=False
)

xgb_importance.to_csv(
    "xgboost_feature_importance.csv",
    index=False
)

lgbm_importance.to_csv(
    "lightgbm_feature_importance.csv",
    index=False
)

prediction_comparison.to_csv(
    "xgboost_lightgbm_predictions.csv",
    index=False
)

print("\n========== FILES CREATED ==========")

print("1. heart_xgboost_lightgbm_cleaned.csv")
print("2. xgboost_lightgbm_model_comparison.csv")
print("3. xgboost_feature_importance.csv")
print("4. lightgbm_feature_importance.csv")
print("5. xgboost_lightgbm_predictions.csv")

# Download main dataset
files.download(
    "heart_xgboost_lightgbm_cleaned.csv"
)

print("\n====================================================")
print("PROJECT 10 COMPLETED SUCCESSFULLY!")
print("====================================================")

print("\nModels used:")
print("✓ XGBoost")
print("✓ LightGBM")
print("✓ SHAP Explainability")

print("\nYou can now compare:")
print("→ Accuracy")
print("→ Precision")
print("→ Recall")
print("→ F1 Score")
print("→ ROC-AUC")
print("→ Feature Importance")
print("→ SHAP explanations")