# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqCSvOcGdDlZQ7IYrYCAnrHims3MYiqL
"""

# ============================================================
# PROJECT 8
# HEART DISEASE — DECISION TREE CLASSIFICATION
# COMPLETE GOOGLE COLAB CODE — ONE CELL
# ============================================================

# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

from google.colab import files

print("=" * 70)
print("HEART DISEASE — DECISION TREE CLASSIFICATION")
print("=" * 70)


# ============================================================
# 2. LOAD UCI CLEVELAND HEART DISEASE DATASET
# ============================================================

columns = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal",
    "num"
]

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"

try:

    df = pd.read_csv(
        url,
        names=columns,
        na_values="?"
    )

    print("\nDataset downloaded from UCI successfully!")

except Exception as e:

    print("\nOnline download failed.")
    print("Please upload the Cleveland dataset manually.")

    uploaded = files.upload()

    file_name = next(iter(uploaded))

    df = pd.read_csv(
        file_name,
        names=columns,
        na_values="?"
    )

    print("\nDataset uploaded successfully!")


# ============================================================
# 3. DISPLAY DATASET
# ============================================================

print("\nDataset Shape:", df.shape)

print("\nFirst 5 Rows:")
display(df.head())


# ============================================================
# 4. DATASET INFORMATION
# ============================================================

print("\n" + "=" * 70)
print("DATASET INFORMATION")
print("=" * 70)

df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nStatistical Summary:")
display(df.describe().T)


# ============================================================
# 5. CLEAN DATA
# ============================================================

# Convert all columns to numeric
for col in df.columns:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

# Remove duplicate rows
df = df.drop_duplicates()

# Fill missing values with median
for col in df.columns:

    if df[col].isnull().sum() > 0:

        df[col] = df[col].fillna(
            df[col].median()
        )

print("\nMissing values after cleaning:")
print(df.isnull().sum())


# ============================================================
# 6. CONVERT TARGET
# ============================================================

# Original UCI target:
# 0 = no disease
# 1,2,3,4 = presence of disease

df["target"] = (
    df["num"] > 0
).astype(int)

# Remove original target column
df = df.drop(
    "num",
    axis=1
)

print("\nTarget Distribution:")
print(df["target"].value_counts())

print("\nTarget Meaning:")
print("0 = No Heart Disease")
print("1 = Heart Disease")


# ============================================================
# 7. TARGET VISUALIZATION
# ============================================================

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="target"
)

plt.title(
    "Heart Disease Distribution"
)

plt.xlabel(
    "Target (0 = No Disease, 1 = Disease)"
)

plt.ylabel("Number of Patients")

plt.show()


# ============================================================
# 8. AGE DISTRIBUTION
# ============================================================

plt.figure(figsize=(8,5))

sns.histplot(
    data=df,
    x="age",
    hue="target",
    kde=True,
    bins=25
)

plt.title(
    "Age Distribution by Heart Disease"
)

plt.xlabel("Age")
plt.ylabel("Count")

plt.show()


# ============================================================
# 9. CHOLESTEROL VS HEART DISEASE
# ============================================================

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="target",
    y="chol"
)

plt.title(
    "Cholesterol vs Heart Disease"
)

plt.xlabel(
    "Heart Disease"
)

plt.ylabel(
    "Cholesterol"
)

plt.show()


# ============================================================
# 10. MAXIMUM HEART RATE
# ============================================================

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="target",
    y="thalach"
)

plt.title(
    "Maximum Heart Rate vs Heart Disease"
)

plt.xlabel(
    "Heart Disease"
)

plt.ylabel(
    "Maximum Heart Rate"
)

plt.show()


# ============================================================
# 11. CORRELATION HEATMAP
# ============================================================

plt.figure(figsize=(12,9))

sns.heatmap(
    df.corr(),
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title(
    "Heart Disease Correlation Heatmap"
)

plt.show()


# ============================================================
# 12. DEFINE FEATURES AND TARGET
# ============================================================

X = df.drop(
    "target",
    axis=1
)

y = df["target"]

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget:")
print("target")


# ============================================================
# 13. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)


# ============================================================
# 14. DECISION TREE MODEL
# ============================================================

model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

print("\nDecision Tree trained successfully!")


# ============================================================
# 15. PREDICTIONS
# ============================================================

y_pred = model.predict(
    X_test
)


# ============================================================
# 16. MODEL EVALUATION
# ============================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0
)

print("\n" + "=" * 70)
print("MODEL PERFORMANCE")
print("=" * 70)

print(
    "Accuracy :",
    round(accuracy, 4)
)

print(
    "Precision:",
    round(precision, 4)
)

print(
    "Recall   :",
    round(recall, 4)
)

print(
    "F1 Score :",
    round(f1, 4)
)


# ============================================================
# 17. CLASSIFICATION REPORT
# ============================================================

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            "No Disease",
            "Disease"
        ],
        zero_division=0
    )
)


# ============================================================
# 18. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    y_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        "No Disease",
        "Disease"
    ],
    yticklabels=[
        "No Disease",
        "Disease"
    ]
)

plt.title(
    "Confusion Matrix — Decision Tree"
)

plt.xlabel(
    "Predicted"
)

plt.ylabel(
    "Actual"
)

plt.show()


# ============================================================
# 19. FEATURE IMPORTANCE
# ============================================================

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print("\n" + "=" * 70)
print("FEATURE IMPORTANCE")
print("=" * 70)

display(
    feature_importance
)


# ============================================================
# 20. FEATURE IMPORTANCE GRAPH
# ============================================================

plt.figure(figsize=(10,6))

sns.barplot(
    data=feature_importance,
    x="Importance",
    y="Feature"
)

plt.title(
    "Feature Importance — Decision Tree"
)

plt.xlabel(
    "Importance"
)

plt.ylabel(
    "Feature"
)

plt.show()


# ============================================================
# 21. VISUALIZE DECISION TREE
# ============================================================

plt.figure(
    figsize=(24,14)
)

plot_tree(
    model,
    feature_names=X.columns,
    class_names=[
        "No Disease",
        "Disease"
    ],
    filled=True,
    rounded=True,
    fontsize=9
)

plt.title(
    "Heart Disease Decision Tree"
)

plt.show()


# ============================================================
# 22. ACTUAL VS PREDICTED
# ============================================================

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print("\nActual vs Predicted:")
display(
    comparison.head(20)
)


# ============================================================
# 23. SAVE PREDICTIONS
# ============================================================

comparison.to_csv(
    "heart_disease_decision_tree_predictions.csv",
    index=False
)


# ============================================================
# 24. SAVE FEATURE IMPORTANCE
# ============================================================

feature_importance.to_csv(
    "heart_disease_feature_importance.csv",
    index=False
)


# ============================================================
# 25. SAVE MODEL RESULTS
# ============================================================

results = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],
    "Score": [
        accuracy,
        precision,
        recall,
        f1
    ]
})

results.to_csv(
    "heart_disease_decision_tree_results.csv",
    index=False
)


# ============================================================
# 26. SAVE CLEAN DATASET
# ============================================================

df.to_csv(
    "heart.csv",
    index=False
)

print("\nFiles created:")

print(
    "1. heart.csv"
)

print(
    "2. heart_disease_decision_tree_predictions.csv"
)

print(
    "3. heart_disease_feature_importance.csv"
)

print(
    "4. heart_disease_decision_tree_results.csv"
)


# ============================================================
# 27. DOWNLOAD HEART.CSV
# ============================================================

files.download(
    "heart.csv"
)


# ============================================================
# 28. FINAL CONCLUSION
# ============================================================

print("\n" + "=" * 70)
print("CONCLUSION")
print("=" * 70)

print("""
1. The UCI Cleveland Heart Disease dataset was loaded.
2. Missing values were identified and handled.
3. The original multi-level target was converted into
   binary classification:
      0 = No Disease
      1 = Disease
4. Exploratory Data Analysis was performed.
5. The dataset was divided into training and testing sets.
6. A Decision Tree Classifier was trained.
7. Model performance was evaluated using:
      - Accuracy
      - Precision
      - Recall
      - F1 Score
8. A confusion matrix was generated.
9. Feature importance was calculated.
10. The complete Decision Tree was visualized.
11. The cleaned heart.csv dataset was saved.

Decision Trees are interpretable classification models that
make predictions through a sequence of feature-based rules.
Controlling max_depth and minimum samples helps reduce
overfitting.
""")

print("=" * 70)
print("PROJECT 8 COMPLETED SUCCESSFULLY!")
print("=" * 70)