# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178iiayT_1HzaCAVkWtiSeBA_RLh1S_CJ
"""

# ============================================================
# PROJECT 11: WINE QUALITY CLASSIFICATION
# DECISION TREE + RANDOM FOREST
# FULLY CORRECTED - ONE COLAB CELL
# ============================================================

!pip -q install ucimlrepo

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)

from google.colab import files

# ============================================================
# 1. LOAD WINE QUALITY DATASET
# ============================================================

print("Loading Wine Quality dataset...")

wine = fetch_ucirepo(id=186)

X = wine.data.features.copy()
y = wine.data.targets.copy()

# Make sure target is a Series
if isinstance(y, pd.DataFrame):
    y = y.iloc[:, 0]

# Combine features + target
df = X.copy()
df["quality"] = y.values

print("\nDataset loaded successfully!")
print("Original shape:", df.shape)

# ============================================================
# 2. FIX COLUMN NAMES
# ============================================================

# Normalize column names
df.columns = (
    df.columns
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace("_", " ", regex=False)
)

print("\n========== COLUMN NAMES ==========")
print(df.columns.tolist())

# ============================================================
# 3. BASIC DATA INSPECTION
# ============================================================

print("\n========== FIRST 5 ROWS ==========")
display(df.head())

print("\n========== DATASET INFO ==========")
df.info()

print("\n========== MISSING VALUES ==========")
print(df.isnull().sum())

print("\n========== DUPLICATES ==========")
print("Duplicate rows:", df.duplicated().sum())

print("\n========== STATISTICS ==========")
display(df.describe())

# ============================================================
# 4. CLEAN DATA
# ============================================================

# Convert all columns to numeric
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Remove duplicate rows
df = df.drop_duplicates()

# Remove missing rows
df = df.dropna()

print("\nCleaned dataset shape:", df.shape)

# ============================================================
# 5. CHECK QUALITY COLUMN
# ============================================================

if "quality" not in df.columns:
    raise ValueError(
        "Quality column was not found. Available columns: "
        + str(df.columns.tolist())
    )

print("\n========== QUALITY VALUES ==========")
print(df["quality"].value_counts().sort_index())

# ============================================================
# 6. CREATE BINARY TARGET
# ============================================================

# Quality >= 7 = Good Wine
# Quality < 7  = Not Good Wine

df["good quality"] = (
    df["quality"] >= 7
).astype(int)

print("\n========== BINARY TARGET ==========")
print(
    df["good quality"]
    .value_counts()
    .sort_index()
)

print("\n0 = Not Good Wine")
print("1 = Good Wine")

# ============================================================
# 7. EDA - QUALITY DISTRIBUTION
# ============================================================

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="quality"
)

plt.title("Wine Quality Distribution")
plt.xlabel("Wine Quality")
plt.ylabel("Count")

plt.show()

# ============================================================
# 8. EDA - GOOD VS NOT GOOD
# ============================================================

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="good quality"
)

plt.title("Good vs Not Good Wine")
plt.xlabel("0 = Not Good, 1 = Good")
plt.ylabel("Count")

plt.show()

# ============================================================
# 9. FIND ALCOHOL COLUMN AUTOMATICALLY
# ============================================================

alcohol_candidates = [
    col for col in df.columns
    if "alcohol" in col
]

if len(alcohol_candidates) == 0:
    raise ValueError("Alcohol column not found.")

alcohol_col = alcohol_candidates[0]

print("\nAlcohol column:", alcohol_col)

plt.figure(figsize=(9,5))

sns.boxplot(
    data=df,
    x="quality",
    y=alcohol_col
)

plt.title("Alcohol Content vs Wine Quality")
plt.xlabel("Wine Quality")
plt.ylabel("Alcohol")

plt.show()

# ============================================================
# 10. FIND VOLATILE ACIDITY COLUMN AUTOMATICALLY
# ============================================================

volatile_candidates = [
    col for col in df.columns
    if "volatile" in col and "acid" in col
]

if len(volatile_candidates) == 0:
    raise ValueError(
        "Volatile acidity column not found. Available columns: "
        + str(df.columns.tolist())
    )

volatile_col = volatile_candidates[0]

print("Volatile acidity column:", volatile_col)

plt.figure(figsize=(9,5))

sns.boxplot(
    data=df,
    x="quality",
    y=volatile_col
)

plt.title("Volatile Acidity vs Wine Quality")
plt.xlabel("Wine Quality")
plt.ylabel("Volatile Acidity")

plt.show()

# ============================================================
# 11. CORRELATION HEATMAP
# ============================================================

plt.figure(figsize=(13,10))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Wine Quality Correlation Heatmap")

plt.show()

# ============================================================
# 12. FEATURES AND TARGET
# ============================================================

X = df.drop(
    columns=["quality", "good quality"]
)

y = df["good quality"]

print("\n========== FEATURES ==========")
print(X.columns.tolist())

print("\nNumber of features:", X.shape[1])

# ============================================================
# 13. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples :", len(X_test))

# ============================================================
# 14. DECISION TREE MODEL
# ============================================================

dt_model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42
)

dt_model.fit(
    X_train,
    y_train
)

dt_pred = dt_model.predict(X_test)

dt_prob = dt_model.predict_proba(X_test)[:, 1]

print("\nDecision Tree trained successfully!")

# ============================================================
# 15. RANDOM FOREST MODEL
# ============================================================

rf_model = RandomForestClassifier(
    n_estimators=200,
    criterion="gini",
    max_depth=8,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(
    X_train,
    y_train
)

rf_pred = rf_model.predict(X_test)

rf_prob = rf_model.predict_proba(X_test)[:, 1]

print("Random Forest trained successfully!")

# ============================================================
# 16. EVALUATION FUNCTION
# ============================================================

def evaluate_model(name, y_true, y_pred, y_prob):

    accuracy = accuracy_score(
        y_true,
        y_pred
    )

    precision = precision_score(
        y_true,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        zero_division=0
    )

    auc = roc_auc_score(
        y_true,
        y_prob
    )

    print("\n======================================")
    print(name)
    print("======================================")

    print(f"Accuracy  : {accuracy:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1 Score  : {f1:.4f}")
    print(f"ROC-AUC   : {auc:.4f}")

    print("\nClassification Report:")

    print(
        classification_report(
            y_true,
            y_pred,
            target_names=[
                "Not Good Wine",
                "Good Wine"
            ],
            zero_division=0
        )
    )

    return [
        accuracy,
        precision,
        recall,
        f1,
        auc
    ]

# ============================================================
# 17. EVALUATE DECISION TREE
# ============================================================

dt_results = evaluate_model(
    "DECISION TREE",
    y_test,
    dt_pred,
    dt_prob
)

# ============================================================
# 18. EVALUATE RANDOM FOREST
# ============================================================

rf_results = evaluate_model(
    "RANDOM FOREST",
    y_test,
    rf_pred,
    rf_prob
)

# ============================================================
# 19. MODEL COMPARISON
# ============================================================

comparison = pd.DataFrame({

    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],

    "Decision Tree": dt_results,

    "Random Forest": rf_results
})

print("\n========== MODEL COMPARISON ==========")

display(comparison)

# ============================================================
# 20. MODEL COMPARISON GRAPH
# ============================================================

comparison.set_index(
    "Metric"
).plot(
    kind="bar",
    figsize=(10,6)
)

plt.title(
    "Decision Tree vs Random Forest"
)

plt.ylabel("Score")

plt.ylim(0,1)

plt.xticks(
    rotation=0
)

plt.show()

# ============================================================
# 21. DECISION TREE CONFUSION MATRIX
# ============================================================

dt_cm = confusion_matrix(
    y_test,
    dt_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    dt_cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        "Not Good",
        "Good"
    ],
    yticklabels=[
        "Not Good",
        "Good"
    ]
)

plt.title(
    "Decision Tree Confusion Matrix"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

# ============================================================
# 22. RANDOM FOREST CONFUSION MATRIX
# ============================================================

rf_cm = confusion_matrix(
    y_test,
    rf_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    rf_cm,
    annot=True,
    fmt="d",
    cmap="Greens",
    xticklabels=[
        "Not Good",
        "Good"
    ],
    yticklabels=[
        "Not Good",
        "Good"
    ]
)

plt.title(
    "Random Forest Confusion Matrix"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

# ============================================================
# 23. DECISION TREE VISUALIZATION
# ============================================================

plt.figure(figsize=(24,12))

plot_tree(
    dt_model,
    feature_names=X.columns,
    class_names=[
        "Not Good",
        "Good"
    ],
    filled=True,
    rounded=True,
    fontsize=8
)

plt.title(
    "Decision Tree Visualization"
)

plt.show()

# ============================================================
# 24. DECISION TREE FEATURE IMPORTANCE
# ============================================================

dt_importance = pd.DataFrame({

    "Feature": X.columns,

    "Importance":
        dt_model.feature_importances_

})

dt_importance = dt_importance.sort_values(
    by="Importance",
    ascending=False
)

print(
    "\n========== DECISION TREE FEATURE IMPORTANCE =========="
)

display(dt_importance)

plt.figure(figsize=(10,6))

sns.barplot(
    data=dt_importance,
    x="Importance",
    y="Feature"
)

plt.title(
    "Decision Tree Feature Importance"
)

plt.show()

# ============================================================
# 25. RANDOM FOREST FEATURE IMPORTANCE
# ============================================================

rf_importance = pd.DataFrame({

    "Feature": X.columns,

    "Importance":
        rf_model.feature_importances_

})

rf_importance = rf_importance.sort_values(
    by="Importance",
    ascending=False
)

print(
    "\n========== RANDOM FOREST FEATURE IMPORTANCE =========="
)

display(rf_importance)

plt.figure(figsize=(10,6))

sns.barplot(
    data=rf_importance,
    x="Importance",
    y="Feature"
)

plt.title(
    "Random Forest Feature Importance"
)

plt.show()

# ============================================================
# 26. ROC CURVE
# ============================================================

fpr_dt, tpr_dt, _ = roc_curve(
    y_test,
    dt_prob
)

fpr_rf, tpr_rf, _ = roc_curve(
    y_test,
    rf_prob
)

dt_auc = roc_auc_score(
    y_test,
    dt_prob
)

rf_auc = roc_auc_score(
    y_test,
    rf_prob
)

plt.figure(figsize=(8,6))

plt.plot(
    fpr_dt,
    tpr_dt,
    label=f"Decision Tree AUC = {dt_auc:.3f}"
)

plt.plot(
    fpr_rf,
    tpr_rf,
    label=f"Random Forest AUC = {rf_auc:.3f}"
)

plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "ROC Curve Comparison"
)

plt.legend()

plt.show()

# ============================================================
# 27. ACTUAL VS PREDICTED
# ============================================================

prediction_results = pd.DataFrame({

    "Actual": y_test.values,

    "Decision_Tree_Predicted":
        dt_pred,

    "Decision_Tree_Probability":
        dt_prob,

    "Random_Forest_Predicted":
        rf_pred,

    "Random_Forest_Probability":
        rf_prob
})

print(
    "\n========== ACTUAL VS PREDICTED =========="
)

display(
    prediction_results.head(20)
)

# ============================================================
# 28. SAVE CLEANED DATASET
# ============================================================

df.to_csv(
    "wine_quality_cleaned.csv",
    index=False
)

# ============================================================
# 29. SAVE MODEL COMPARISON
# ============================================================

comparison.to_csv(
    "wine_model_comparison.csv",
    index=False
)

# ============================================================
# 30. SAVE DECISION TREE IMPORTANCE
# ============================================================

dt_importance.to_csv(
    "wine_decision_tree_feature_importance.csv",
    index=False
)

# ============================================================
# 31. SAVE RANDOM FOREST IMPORTANCE
# ============================================================

rf_importance.to_csv(
    "wine_random_forest_feature_importance.csv",
    index=False
)

# ============================================================
# 32. SAVE PREDICTIONS
# ============================================================

prediction_results.to_csv(
    "wine_quality_predictions.csv",
    index=False
)

# ============================================================
# 33. DOWNLOAD CLEANED DATASET
# ============================================================

files.download(
    "wine_quality_cleaned.csv"
)

# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n====================================================")
print("PROJECT 11 COMPLETED SUCCESSFULLY!")
print("====================================================")

print("\nModels used:")
print("✓ Decision Tree")
print("✓ Random Forest")

print("\nConcepts covered:")
print("✓ Data Cleaning")
print("✓ Exploratory Data Analysis")
print("✓ Binary Classification")
print("✓ Decision Tree")
print("✓ Random Forest")
print("✓ Feature Importance")
print("✓ Confusion Matrix")
print("✓ ROC-AUC")
print("✓ Model Comparison")

print("\nOutput files:")
print("✓ wine_quality_cleaned.csv")
print("✓ wine_model_comparison.csv")
print("✓ wine_decision_tree_feature_importance.csv")
print("✓ wine_random_forest_feature_importance.csv")
print("✓ wine_quality_predictions.csv")